services:
    boilerplate-prometheus:
        image: prom/prometheus:latest
        container_name: boilerplate-prometheus
        ports:
            - '39090:9090'
        volumes:
            - ../prometheus.yml:/etc/prometheus/prometheus.yml
            - prometheus_data:/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/usr/share/prometheus/console_libraries'
            - '--web.console.templates=/usr/share/prometheus/consoles'
        restart: unless-stopped
        networks:
            - boilerplate-network
        depends_on:
            - boilerplate-server

